services:
  client:
    container_name: thought_client
    build: ./client
    image: debug_client
    ports:
      - 8080:8080
    working_dir: /code
    volumes:
      - type: bind
        source: ./client
        target: /code
    command: ["http-server"]
  api:
    container_name: thought_api
    ports:
      - 3000:3000
    environment:
      - PGUSER=futureproof
      - PGHOST=db
      - PGPASSWORD=password
      - PGDATABASE=example
      - PGPORT=5432
      - NODE_ENV=development
    depends_on:
      - db
    command: bash -c "npm install && npm run dev"
  db:
    container_name: thought_db
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=example
      - POSTGRES_USER=futureproof
      - POSTGRES_PASSWORD=password
volumes:
  dbdata:
networks:
  default:
    name: telegraph
